/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.itson.vista;

import java.util.ArrayList;
import java.util.GregorianCalendar;
import java.util.List;
import javax.swing.JOptionPane;
import org.itson.dao.PersonaDAO;
import org.itson.dominio.Persona;
import org.itson.interfaces.IPersona;

/**
 *
 * @author LoanWeefos
 */
public class FrmPrincipal extends javax.swing.JFrame {
    private IPersona personaDAO;
    /**
     * Creates new form principal
     */
    public FrmPrincipal() {
        initComponents();
        personaDAO = new PersonaDAO();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        btnLicencias = new javax.swing.JButton();
        btnPlacas = new javax.swing.JButton();
        btnConsultas = new javax.swing.JButton();
        btnReportes = new javax.swing.JButton();
        btnAgregarPersonas = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblTitulo.setFont(new java.awt.Font("Yu Gothic UI", 1, 36)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(105, 28, 50));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Sistema de placas y licencias");
        lblTitulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnLicencias.setBackground(new java.awt.Color(159, 34, 65));
        btnLicencias.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLicencias.setForeground(new java.awt.Color(255, 255, 255));
        btnLicencias.setText("Módulo de licencias");
        btnLicencias.setBorderPainted(false);
        btnLicencias.setFocusPainted(false);
        btnLicencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLicenciasActionPerformed(evt);
            }
        });

        btnPlacas.setBackground(new java.awt.Color(159, 34, 65));
        btnPlacas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPlacas.setForeground(new java.awt.Color(255, 255, 255));
        btnPlacas.setText("Módulo de placas");
        btnPlacas.setBorderPainted(false);
        btnPlacas.setFocusPainted(false);
        btnPlacas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlacasActionPerformed(evt);
            }
        });

        btnConsultas.setBackground(new java.awt.Color(159, 34, 65));
        btnConsultas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnConsultas.setForeground(new java.awt.Color(255, 255, 255));
        btnConsultas.setText("Módulo de consultas");
        btnConsultas.setBorderPainted(false);
        btnConsultas.setFocusPainted(false);
        btnConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultasActionPerformed(evt);
            }
        });

        btnReportes.setBackground(new java.awt.Color(159, 34, 65));
        btnReportes.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnReportes.setForeground(new java.awt.Color(255, 255, 255));
        btnReportes.setText("Módulo de reportes");
        btnReportes.setBorderPainted(false);
        btnReportes.setFocusPainted(false);
        btnReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportesActionPerformed(evt);
            }
        });

        btnAgregarPersonas.setBackground(new java.awt.Color(159, 34, 65));
        btnAgregarPersonas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAgregarPersonas.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarPersonas.setText("Agregar personas");
        btnAgregarPersonas.setBorderPainted(false);
        btnAgregarPersonas.setFocusPainted(false);
        btnAgregarPersonas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarPersonasActionPerformed(evt);
            }
        });

        btnSalir.setBackground(new java.awt.Color(159, 34, 65));
        btnSalir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("Salir");
        btnSalir.setBorderPainted(false);
        btnSalir.setFocusPainted(false);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAgregarPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnConsultas, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnLicencias, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(btnPlacas, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34))
            .addComponent(lblTitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLicencias, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPlacas, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConsultas, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnAgregarPersonasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarPersonasActionPerformed
        this.insertarPersonas();
    }//GEN-LAST:event_btnAgregarPersonasActionPerformed

    private void btnLicenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLicenciasActionPerformed
        new FrmLicencia().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLicenciasActionPerformed

    private void btnPlacasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlacasActionPerformed
        new FrmPlaca().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPlacasActionPerformed

    private void btnConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultasActionPerformed
        new FrmConsulta().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnConsultasActionPerformed

    private void btnReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesActionPerformed
        new FrmReporte().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnReportesActionPerformed

    private List<Persona> lista20Personas(){
        Persona persona1 = new Persona(  "1", "Jorge", "Sánchez", "Quezada", "6441234567", new GregorianCalendar(1995, 5, 15));
        Persona persona2 = new Persona(  "2", "Mario", "Díaz", "Padilla", "6442345678", new GregorianCalendar(2003, 11, 25));
        Persona persona3 = new Persona(  "3", "Gabriel", "Mancinas", "Cota", "6443456789", new GregorianCalendar(1992, 2, 12));
        Persona persona4 = new Persona(  "4", "Julio", "Chon", "Obeso", "6444567890", new GregorianCalendar(1989, 11, 7));
        Persona persona5 = new Persona(  "5", "Gibran", "Duran", "Solano", "6445678901", new GregorianCalendar(1998, 6, 30));
        Persona persona6 = new Persona(  "6", "María", "Pérez", "Rodríguez", "6446789012", new GregorianCalendar(2002, 9, 18));
        Persona persona7 = new Persona(  "7", "Juan", "Gutiérrez", "Fernández", "6447890123", new GregorianCalendar(1987, 4, 25));
        Persona persona8 = new Persona(  "8", "Laura", "Díaz", "Sánchez", "6448901234", new GregorianCalendar(1997, 1, 5));
        Persona persona9 = new Persona(  "9", "Alejandro", "Ramírez", "González", "6449012345", new GregorianCalendar(1990, 7, 19));
        Persona persona10 = new Persona("10", "Isabel", "Herrera", "Santos", "6444321098", new GregorianCalendar(1999, 12, 3));
        Persona persona11 = new Persona("11", "Arturo", "Vargas", "Montes", "6445432109", new GregorianCalendar(1996, 10, 29));
        Persona persona12 = new Persona("12", "Rosa", "Álvarez", "Guzmán", "6446543210", new GregorianCalendar(1991, 8, 17));
        Persona persona13 = new Persona("13", "Manuel", "Castillo", "Díaz", "6447654321", new GregorianCalendar(2001, 6, 11));
        Persona persona14 = new Persona("14", "Mónica", "López", "Soto", "6448765432", new GregorianCalendar(1994, 3, 2));
        Persona persona15 = new Persona("15", "Eduardo", "Flores", "Ortega", "6449876543", new GregorianCalendar(1993, 12, 21));
        Persona persona16 = new Persona("16", "Lucía", "Peralta", "Romero", "6440987654", new GregorianCalendar(1997, 9, 9));
        Persona persona17 = new Persona("17", "Diego", "Gómez", "Castro", "6445432109", new GregorianCalendar(1995, 6, 17));
        Persona persona18 = new Persona("18", "Carmen", "Santos", "García", "6444321098", new GregorianCalendar(1990, 11, 27));
        Persona persona19 = new Persona("19", "Elena", "Moreno", "Núñez", "6443210987", new GregorianCalendar(1998, 4, 7));
        Persona persona20 = new Persona("20", "Diego", "Gómez", "Castro", "6445432109", new GregorianCalendar(1995, 6, 17));
        List<Persona> personas = new ArrayList<>();
        personas.add(persona1);
        personas.add(persona2);
        personas.add(persona3);
        personas.add(persona4);
        personas.add(persona5);
        personas.add(persona6);
        personas.add(persona7);
        personas.add(persona8);
        personas.add(persona9);
        personas.add(persona10);
        personas.add(persona11);
        personas.add(persona12);
        personas.add(persona13);
        personas.add(persona14);
        personas.add(persona15);
        personas.add(persona16);
        personas.add(persona17);
        personas.add(persona18);
        personas.add(persona19);
        personas.add(persona20);
        return personas;
    }
    private void insertarPersonas() {
        List<Persona> personas = lista20Personas();
        System.out.println(lista20Personas());
        System.out.println(personaDAO.consultarTodos());
        
        if (personaDAO.consultarTodos().size() == 20) {
            JOptionPane.showMessageDialog(null, "Ya se han insertado las 20 personas", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            for (Persona persona : personas) {
                personaDAO.agregarPersona(persona);
            }
            JOptionPane.showMessageDialog(this, "Se han insertado las 20 personas");
        }

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarPersonas;
    private javax.swing.JButton btnConsultas;
    private javax.swing.JButton btnLicencias;
    private javax.swing.JButton btnPlacas;
    private javax.swing.JButton btnReportes;
    private javax.swing.JButton btnSalir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
