/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.itson.vista;

import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.List;
import javax.swing.JOptionPane;
import org.itson.dao.PersonaDAO;
import org.itson.dao.PlacaDAO;
import org.itson.dao.AutomovilDAO;
import org.itson.dominio.Persona;
import org.itson.dominio.Placa;
import org.itson.interfaces.IPersona;
import org.itson.interfaces.IPlaca;
import org.apache.commons.lang3.RandomStringUtils;
import org.itson.dao.VehiculoDAO;
import org.itson.dominio.Automovil;
import org.itson.dominio.Tramite;
import org.itson.dominio.Vehiculo;
import org.itson.enums.EnumCostosPlacas;
import org.itson.interfaces.IAutomovil;
import org.itson.interfaces.IVehiculo;

/**
 *
 * @author LoanWeefos
 */
public class FrmRegistrarPlaca extends javax.swing.JFrame {

    private Persona persona;
    private IAutomovil automovilDAO;
    private IVehiculo vehiculoDAO;
    private IPlaca placaDAO;
    private IPersona personaDAO;
    private boolean esNuevo;
    private String numSerie;

    /**
     * Creates new form registrarPlacas
     */
    public FrmRegistrarPlaca(Persona persona, Boolean esNuevo, String numSerie) {
        initComponents();
        this.esNuevo = esNuevo;
        this.numSerie = numSerie;
        this.vehiculoDAO = new VehiculoDAO();
        this.cambiarPorTipo();
        this.persona = persona;
        this.automovilDAO = new AutomovilDAO();
        this.placaDAO = new PlacaDAO();
        this.personaDAO = new PersonaDAO();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblRegistrar = new javax.swing.JLabel();
        lblCosto = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        lblMarca = new javax.swing.JLabel();
        lblSerie = new javax.swing.JLabel();
        txtMarca = new javax.swing.JTextField();
        lblLinea = new javax.swing.JLabel();
        txtLinea = new javax.swing.JTextField();
        lblColor = new javax.swing.JLabel();
        txtColor = new javax.swing.JTextField();
        lblModelo = new javax.swing.JLabel();
        txtModelo = new javax.swing.JTextField();
        txtSerie = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Módulo de placas");
        lblTitulo.setFont(new java.awt.Font("Yu Gothic UI", 1, 36)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(105, 28, 50));
        lblTitulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblRegistrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRegistrar.setText("Registrar vehículo y generar placas");
        lblRegistrar.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblRegistrar.setForeground(new java.awt.Color(105, 28, 50));

        lblCosto.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCosto.setText("Costo: $");
        lblCosto.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblCosto.setForeground(new java.awt.Color(105, 28, 50));

        lblTotal.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(105, 28, 50));

        btnRegistrar.setText("Registrar");
        btnRegistrar.setBackground(new java.awt.Color(159, 34, 65));
        btnRegistrar.setBorderPainted(false);
        btnRegistrar.setFocusPainted(false);
        btnRegistrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnRegresar.setText("Regresar");
        btnRegresar.setBackground(new java.awt.Color(159, 34, 65));
        btnRegresar.setBorderPainted(false);
        btnRegresar.setFocusPainted(false);
        btnRegresar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        lblMarca.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMarca.setText("Marca:");
        lblMarca.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblMarca.setForeground(new java.awt.Color(105, 28, 50));

        lblSerie.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSerie.setText("Serie:");
        lblSerie.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblSerie.setForeground(new java.awt.Color(105, 28, 50));

        txtMarca.setToolTipText("");

        lblLinea.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblLinea.setText("Línea:");
        lblLinea.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblLinea.setForeground(new java.awt.Color(105, 28, 50));

        txtLinea.setToolTipText("");

        lblColor.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblColor.setText("Color:");
        lblColor.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblColor.setForeground(new java.awt.Color(105, 28, 50));

        txtColor.setToolTipText("");
        txtColor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtColorKeyTyped(evt);
            }
        });

        lblModelo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblModelo.setText("Modelo:");
        lblModelo.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblModelo.setForeground(new java.awt.Color(105, 28, 50));

        txtModelo.setToolTipText("");

        txtSerie.setToolTipText("");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblRegistrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblModelo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblSerie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblLinea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(5, 5, 5)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtModelo)
                                    .addComponent(txtSerie)
                                    .addComponent(txtLinea)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lblMarca, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                                    .addComponent(lblColor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(6, 6, 6)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtColor, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(lblCosto, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
            .addComponent(lblTitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblTitulo)
                .addGap(18, 18, 18)
                .addComponent(lblRegistrar)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSerie)
                    .addComponent(txtSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLinea)
                    .addComponent(txtLinea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblModelo)
                    .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMarca)
                    .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblColor)
                    .addComponent(txtColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblCosto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(79, 79, 79))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        new FrmVehiculos(persona).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        if (esNuevo) {
            if (vehiculoDAO.verificarExistencia(extraerDatosFormulario().getNumero())) {
                JOptionPane.showMessageDialog(null, "El vehículo con ese número de serie ya se encuentra registrado.\nFavor de dirigirse a la sección CAMBIAR PLACA.", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                guardar();
                personaDAO.actualizarPersona(persona);
                JOptionPane.showMessageDialog(null, "Se han tramitado las placas y registrado el vehículo correctamente");
                this.dispose();
                new FrmVehiculos(persona).setVisible(true);
            }
        } else {
            Vehiculo vehiculo = vehiculoDAO.consultarVehiculo(numSerie);
            placaDAO.actualizarPlaca(vehiculo);
            guardar();
            personaDAO.actualizarPersona(persona);
            JOptionPane.showMessageDialog(null, "Se han cambiado las placas correctamente");
            this.dispose();
            new FrmVehiculos(persona).setVisible(true);
        }

    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void txtColorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtColorKeyTyped
        char c = evt.getKeyChar();
        if ((c < 'a' || c > 'z') && (c < 'A' || c > 'Z')) {
            evt.consume();
        } 
    }//GEN-LAST:event_txtColorKeyTyped

    private String generarNumPlaca() {
        String numPlaca = RandomStringUtils.randomAlphabetic(3).toUpperCase() + "-" + RandomStringUtils.randomNumeric(3);
        if (placaDAO.verificarExistencia(numPlaca)) {
            return generarNumPlaca();
        } else {
            return numPlaca;
        }
    }

    private void cambiarPorTipo() {
        if (esNuevo) {
            lblTotal.setText(String.valueOf(EnumCostosPlacas.NUEVO.getCosto()));
        } else {
            lblTotal.setText(String.valueOf(EnumCostosPlacas.USADO.getCosto()));
            lblRegistrar.setText("Cambiar placas");
            Vehiculo vehiculo = vehiculoDAO.consultarVehiculo(numSerie);
            txtSerie.setText(vehiculo.getNumero());
            txtLinea.setText(vehiculo.getLinea());
            txtModelo.setText(vehiculo.getModelo());
            txtMarca.setText(vehiculo.getMarca());
            txtColor.setText(vehiculo.getColor());

            txtSerie.setEnabled(false);
            txtLinea.setEnabled(false);
            txtModelo.setEnabled(false);
            txtMarca.setEnabled(false);
            txtColor.setEnabled(false);
            btnRegistrar.setText("Cambiar");
        }
    }

    private Placa generarPlaca() {
        String nombrePersona = persona.getNombre() + " " + persona.getApellidoPaterno() + " " + persona.getApellidoMaterno();
        Calendar fechaExpedicion = new GregorianCalendar();
        return new Placa(generarNumPlaca(), fechaExpedicion, fechaExpedicion, true, extraerDatosFormulario(), nombrePersona, Float.valueOf(lblTotal.getText()), persona);

    }

    private Automovil extraerDatosFormulario() {
        this.numSerie = txtSerie.getText();
        String linea = txtLinea.getText();
        String modelo = txtModelo.getText();
        String marca = txtMarca.getText();
        String color = txtColor.getText();

        return new Automovil(numSerie, marca, linea, color, modelo, persona);
    }

    private void guardar() {
        if (esNuevo) {
            Automovil automovil = extraerDatosFormulario();
            automovilDAO.agregarAutomovil(automovil);
            List<Vehiculo> listaVehiculo = persona.getVehiculos();
            listaVehiculo.add(automovil);
            persona.setVehiculos(listaVehiculo);
        }

        Placa placa = generarPlaca();
        placaDAO.agregarPlaca(placa);
        List<Tramite> listaTramites = persona.getTramites();
        listaTramites.add(placa);
        persona.setTramites(listaTramites);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblColor;
    private javax.swing.JLabel lblCosto;
    private javax.swing.JLabel lblLinea;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblModelo;
    private javax.swing.JLabel lblRegistrar;
    private javax.swing.JLabel lblSerie;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTextField txtColor;
    private javax.swing.JTextField txtLinea;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtSerie;
    // End of variables declaration//GEN-END:variables
}
